# Generated by Django 4.0.3 on 2022-03-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projecto',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tecnologia',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='titulo',
            new_name='title',
        ),
    ]
